name: Build, Test, and Deploy to MonsterASP.NET
on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
          
      - name: Restore dependencies
        run: dotnet restore QiBalance.sln
        
      - name: Build solution
        run: dotnet build QiBalance.sln --configuration Release --no-restore
        
      - name: Run unit tests
        run: dotnet test QiBalance.Tests/QiBalance.Tests.csproj --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults/*.trx

  build_and_deploy:
    name: Build and Deploy
    runs-on: windows-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
          
      - name: Restore dependencies
        run: dotnet restore QiBalance.sln
        
      - name: Publish application
        run: dotnet publish ./QiBalance/QiBalance.csproj --configuration Release --output ./publish --no-restore

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
