name: Test Coverage Report

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-coverage:
    name: Generate Test Coverage Report
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
          
      - name: Restore dependencies
        run: dotnet restore QiBalance.sln
        
      - name: Build solution
        run: dotnet build QiBalance.sln --configuration Release --no-restore
        
      - name: Install coverlet tool
        run: dotnet tool install --global coverlet.console
        
      - name: Run tests with coverage
        run: dotnet test QiBalance.Tests/QiBalance.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory TestResults
        
      - name: Generate coverage report
        run: dotnet tool install --global dotnet-reportgenerator-globaltool && reportgenerator -reports:"TestResults/*/coverage.cobertura.xml" -targetdir:"TestResults/CoverageReport" -reporttypes:Html
        
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: TestResults/CoverageReport/
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: TestResults/*/coverage.cobertura.xml
          fail_ci_if_error: false 